/*
DONT FORGET TO PUT DELETE BUTTON BESIDE CHECKBOX good

RENDER ARRAY TO PRIORITIZE DATA WITHOUT CHECKS BEFORE RENDERING CHECKED STUDENTS

REMIND TO LOCK INVITES WHEN GROUP CHAT IS FULL

AMPOGI NG PROGRAMMER
*/