import {studentList} from "../data/studentList.js";
import {initFunctions} from "./functions.js";

// Renders the studentList inside the webpage
export function renderStudentChecklist() {

  // Initializes the studentList's HTML code
  let studentChecklistHTML = '';

  // Loops through all students stored in studentList and add each item
  // inside studentChecklistHTML for rendering

  // All options are set with unique ids to properly handle 
  // modifications in the webpage
  studentList.forEach((student) => {
    const id = student.id;
    const name = student.name;

    const html = `
      <div class="student-info">

        <button class="edit-button js-edit-button" data-id="${id}">
          <img class="edit-img" src="../images/edit-icon.png">
        </button>

        <div class="student-name-container js-student-name-container-${id}">
          <div class="student-name">${name}</div>
        </div>

        <div class="student-options">
          <input class="checkbox js-checkbox js-checkbox-${id}" type="checkbox" data-id="${id}">
          <div class="delete-button-container js-delete-button-container-${id}">
              <button class="delete-button js-delete-button" data-id="${id}">x</button>
          </div>
        </div>

      </div>
    `;

    studentChecklistHTML += html;
  });

  // Sets the HTML generated by the loop
  document.querySelector('.js-students-checklist-container').innerHTML = studentChecklistHTML;

  // Initializes the functions and renders the checkbox's status for 
  // each student
  initFunctions();
};
